services:
  - type: web
    name: surface-defect-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. streamlit run app.py --server.port 10000 --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
